// pages/detail/detail.js
Page({

    /**
     * 页面的初始数据
     */
    data: {
        title: '',
        clipDesc: true,
        actors:[
            {
                "user":null,
                "roles":[
                    "导演",
                    "演员",
                    "制片人"
                ],
                "latin_name":"David Yates",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1275147/",
                "abstract":"大卫·叶茨，英国电影导演。曾在美国华盛顿居住一年，之后返回伦敦的国家电影电视学院学习。是著名导演...",
                "title":"大卫·叶茨（同名）英国,默西塞德郡,圣海伦斯影视演员",
                "character":"导演",
                "uri":"douban://douban.com/celebrity/1275147?subject_id=27504202",
                "cover_url":"https://img3.doubanio.com/view/celebrity/raw/public/p9900.jpg",
                "avatar":{
                    "large":"https://img3.doubanio.com/view/celebrity/raw/public/p9900.jpg",
                    "normal":"https://img3.doubanio.com/view/celebrity/raw/public/p9900.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1275147/",
                "type":"celebrity",
                "id":"1275147",
                "name":"大卫·叶茨"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音"
                ],
                "latin_name":"Eddie Redmayne",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1010503/",
                "abstract":"埃迪·雷德梅尼1982年出生于伦敦，曾就读于伊顿公学，2003年从剑桥三一学院毕业。他是英国国家青年剧团...",
                "title":"埃迪·雷德梅恩（同名）英国,伦敦影视演员",
                "character":"饰 Newt Scamander",
                "uri":"douban://douban.com/celebrity/1010503?subject_id=27216194",
                "cover_url":"https://img9.doubanio.com/view/celebrity/raw/public/p1415126644.85.jpg",
                "avatar":{
                    "large":"https://img9.doubanio.com/view/celebrity/raw/public/p1415126644.85.jpg",
                    "normal":"https://img9.doubanio.com/view/celebrity/raw/public/p1415126644.85.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1010503/",
                "type":"celebrity",
                "id":"1010503",
                "name":"埃迪·雷德梅恩"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音",
                    "制片人",
                    "导演"
                ],
                "latin_name":"Jude Law",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1010510/",
                "abstract":"　　修长的身材、微卷的浅棕色头发、海洋般绿蓝交织的双眼，英国演员裘德·洛—这个好看得让人叹息的英...",
                "title":"裘德·洛（同名）英国,伦敦,刘易舍姆影视演员",
                "character":"饰 Albus Dumbledore",
                "uri":"douban://douban.com/celebrity/1010510?subject_id=27216201",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p4952.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p4952.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p4952.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1010510/",
                "type":"celebrity",
                "id":"1010510",
                "name":"裘德·洛"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音",
                    "制片人"
                ],
                "latin_name":"Mads Mikkelsen",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1040529/",
                "abstract":"麦德斯·米科尔森，丹麦著名男演员。米科尔森是世纪之交丹麦电影发展新的黄金期造就的一颗巨星，也是世...",
                "title":"麦斯·米科尔森（同名）丹麦,哥本哈根影视演员",
                "character":"饰 Grindelwald",
                "uri":"douban://douban.com/celebrity/1040529?subject_id=27246283",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p57893.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p57893.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p57893.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1040529/",
                "type":"celebrity",
                "id":"1040529",
                "name":"麦斯·米科尔森"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音",
                    "导演",
                    "编剧",
                    "制片人"
                ],
                "latin_name":"Dan Fogler",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1027317/",
                "abstract":"",
                "title":"丹·福勒（同名）美国,纽约,布鲁克林影视演员",
                "character":"饰 Jacob Kowalski",
                "uri":"douban://douban.com/celebrity/1027317?subject_id=27233053",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p31252.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p31252.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p31252.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1027317/",
                "type":"celebrity",
                "id":"1027317",
                "name":"丹·福勒"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "音乐"
                ],
                "latin_name":"Alison Sudol",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1350625/",
                "abstract":"艾莉森·罗兰·萨多尔是一名美国创作型歌手、钢琴家和演员。她在音乐界的被称为美丽瞬间（英语：A Fine ...",
                "title":"艾莉森·萨多尔（同名）美国,华盛顿州,西雅图影视演员",
                "character":"饰 Queenie Goldstein",
                "uri":"douban://douban.com/celebrity/1350625?subject_id=27550204",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1479957534.38.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1479957534.38.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1479957534.38.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1350625/",
                "type":"celebrity",
                "id":"1350625",
                "name":"艾莉森·萨多尔"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Katherine Waterston",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1316589/",
                "abstract":"出生于1980年3月3日的凯瑟琳·沃特斯顿是美国人，其父是老牌电影演员萨姆·沃特森。2007年她首次在故事...",
                "title":"凯瑟琳·沃特斯顿（同名）英国,伦敦,威斯敏斯特影视演员",
                "character":"饰 Tina Goldstein",
                "uri":"douban://douban.com/celebrity/1316589?subject_id=27497568",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1515450935.22.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1515450935.22.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1515450935.22.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1316589/",
                "type":"celebrity",
                "id":"1316589",
                "name":"凯瑟琳·沃特斯顿"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音"
                ],
                "latin_name":"Ezra Miller",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1313037/",
                "abstract":"埃兹拉·米勒是一位多才多艺的90后演员，不仅涉猎影视，还是位优秀的歌者。  　　米勒出生在新泽西...",
                "title":"埃兹拉·米勒（同名）美国,新泽西州,Wyckoff影视演员",
                "character":"饰 Credence Barebone / Aurelius Dumbledore",
                "uri":"douban://douban.com/celebrity/1313037?subject_id=27493514",
                "cover_url":"https://img9.doubanio.com/view/celebrity/raw/public/p1357544568.85.jpg",
                "avatar":{
                    "large":"https://img9.doubanio.com/view/celebrity/raw/public/p1357544568.85.jpg",
                    "normal":"https://img9.doubanio.com/view/celebrity/raw/public/p1357544568.85.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1313037/",
                "type":"celebrity",
                "id":"1313037",
                "name":"埃兹拉·米勒"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "导演",
                    "编剧"
                ],
                "latin_name":"Callum Turner",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1328007/",
                "abstract":"特纳1990年2月15日出生于英国伦敦，演员，模特。2010年，卡勒姆·特纳为赫特福德大学的电视节目出演了他...",
                "title":"卡勒姆·特纳（同名）英国,伦敦,切尔西影视演员",
                "character":"饰 Theseus Scamander",
                "uri":"douban://douban.com/celebrity/1328007?subject_id=27481450",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1430825915.83.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1430825915.83.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1430825915.83.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1328007/",
                "type":"celebrity",
                "id":"1328007",
                "name":"卡勒姆·特纳"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Jessica Williams",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1189267/",
                "abstract":"Jessica Williams is an actress, known for The Daily Show (1996), Delivery Man (2013) and Hot Tub ...",
                "title":"杰西卡·威廉姆斯（同名）美国,加利福尼亚州影视演员",
                "character":"饰 Eulalie Hicks",
                "uri":"douban://douban.com/celebrity/1189267?subject_id=27395219",
                "cover_url":"https://img9.doubanio.com/view/celebrity/raw/public/p1499136016.86.jpg",
                "avatar":{
                    "large":"https://img9.doubanio.com/view/celebrity/raw/public/p1499136016.86.jpg",
                    "normal":"https://img9.doubanio.com/view/celebrity/raw/public/p1499136016.86.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1189267/",
                "type":"celebrity",
                "id":"1189267",
                "name":"杰西卡·威廉姆斯"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Richard Coyle",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1031846/",
                "abstract":"他曾经是Coupling 里的第六维搞笑天才——Jeffrey Murdock 。为了不被喜剧定型，他第四季就闪人了。最新...",
                "title":"理查德·柯伊尔（同名）英国,英格兰,约克郡,谢菲尔德影视演员",
                "character":"饰 Aberforth Dumbledore",
                "uri":"douban://douban.com/celebrity/1031846?subject_id=27237587",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1022.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1022.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1022.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1031846/",
                "type":"celebrity",
                "id":"1031846",
                "name":"理查德·柯伊尔"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Poppy Corby-Tuech",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1337282/",
                "abstract":"on",
                "title":"波佩·科比-特曲（同名）法国影视演员",
                "character":"饰 Vinda Rosier",
                "uri":"douban://douban.com/celebrity/1337282?subject_id=27497856",
                "cover_url":"https://img9.doubanio.com/view/celebrity/raw/public/p1491111938.56.jpg",
                "avatar":{
                    "large":"https://img9.doubanio.com/view/celebrity/raw/public/p1491111938.56.jpg",
                    "normal":"https://img9.doubanio.com/view/celebrity/raw/public/p1491111938.56.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1337282/",
                "type":"celebrity",
                "id":"1337282",
                "name":"波佩·科比-特曲"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Victoria Yeates",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1397745/",
                "abstract":"Victoria Natalie Yeates is an English actress. She is best known for her role as Sister Winifred ...",
                "title":"维多利亚·耶茨（同名）英国,多塞特郡,伯恩茅斯影视演员",
                "character":"饰 Bunty",
                "uri":"douban://douban.com/celebrity/1397745?subject_id=30279371",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1533276732.63.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1533276732.63.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1533276732.63.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1397745/",
                "type":"celebrity",
                "id":"1397745",
                "name":"维多利亚·耶茨"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音"
                ],
                "latin_name":"William Nadylam",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1361420/",
                "abstract":"",
                "title":"威廉·纳迪兰（同名）法国,蒙彼利埃影视演员",
                "character":"饰 Yusuf Kama",
                "uri":"douban://douban.com/celebrity/1361420?subject_id=27490952",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1541745550.88.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1541745550.88.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1541745550.88.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1361420/",
                "type":"celebrity",
                "id":"1361420",
                "name":"威廉·纳迪兰"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音"
                ],
                "latin_name":"Oliver Masucci",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1356578/",
                "abstract":"Oliver Masucci is a German actor. He is best known for the role of Adolf Hitler in the 2015 film ...",
                "title":"奥利弗·马苏奇（同名）德国,巴登-符腾堡州,斯图加特影视演员",
                "character":"饰 Anton Vogel",
                "uri":"douban://douban.com/celebrity/1356578?subject_id=27578217",
                "cover_url":"https://img3.doubanio.com/view/celebrity/raw/public/p1537500367.0.jpg",
                "avatar":{
                    "large":"https://img3.doubanio.com/view/celebrity/raw/public/p1537500367.0.jpg",
                    "normal":"https://img3.doubanio.com/view/celebrity/raw/public/p1537500367.0.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1356578/",
                "type":"celebrity",
                "id":"1356578",
                "name":"奥利弗·马苏奇"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Valerie Pachner",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1376990/",
                "abstract":"",
                "title":"瓦莱丽·帕赫纳（同名）奥地利,韦尔斯影视演员",
                "character":"饰 Henrietta Fischer",
                "uri":"douban://douban.com/celebrity/1376990?subject_id=27585508",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1499848867.97.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1499848867.97.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1499848867.97.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1376990/",
                "type":"celebrity",
                "id":"1376990",
                "name":"瓦莱丽·帕赫纳"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Aleksandr Kuznetsov",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1400621/",
                "abstract":"",
                "title":"亚历山大·库兹涅佐夫（同名）俄罗斯影视演员",
                "character":"饰 Helmut",
                "uri":"douban://douban.com/celebrity/1400621?subject_id=30323124",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1536648173.12.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1536648173.12.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1536648173.12.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1400621/",
                "type":"celebrity",
                "id":"1400621",
                "name":"亚历山大·库兹涅佐夫"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Ramona Kunze-Libnow",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1371863/",
                "abstract":"",
                "title":"拉莫娜·库泽-莉比诺（同名）德国,Barneberg影视演员",
                "character":"饰 Edith",
                "uri":"douban://douban.com/celebrity/1371863?subject_id=27587272",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1496203756.71.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1496203756.71.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1496203756.71.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1371863/",
                "type":"celebrity",
                "id":"1371863",
                "name":"拉莫娜·库泽-莉比诺"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Maria Fernanda Cândido",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1069306/",
                "abstract":"",
                "title":"马丽娅·费尔南达·康基多（同名）巴西,巴拉那,隆德里纳影视演员",
                "character":"饰 Vicência Santos",
                "uri":"douban://douban.com/celebrity/1069306?subject_id=27275052",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1515223263.91.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1515223263.91.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1515223263.91.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1069306/",
                "type":"celebrity",
                "id":"1069306",
                "name":"马丽娅·费尔南达·康基多"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Dave Wong  ",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1468526/",
                "abstract":"",
                "title":"戴夫·王（同名）None影视演员",
                "character":"饰 Liu Tao",
                "uri":"douban://douban.com/celebrity/1468526?subject_id=35779906",
                "cover_url":"https://img1.doubanio.com/view/personage/raw/public/296e37935c658368897e575625b9c86a.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/personage/raw/public/296e37935c658368897e575625b9c86a.jpg",
                    "normal":"https://img1.doubanio.com/view/personage/raw/public/296e37935c658368897e575625b9c86a.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1468526/",
                "type":"celebrity",
                "id":"1468526",
                "name":"戴夫·王"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Wilf Scolding",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1422221/",
                "abstract":"",
                "title":"维尔夫·斯科尔丁（同名）英国影视演员",
                "character":"饰 Workman",
                "uri":"douban://douban.com/celebrity/1422221?subject_id=34807576",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/pnCRlfuR43LIcel_avatar_uploaded1566405501.12.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/pnCRlfuR43LIcel_avatar_uploaded1566405501.12.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/pnCRlfuR43LIcel_avatar_uploaded1566405501.12.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1422221/",
                "type":"celebrity",
                "id":"1422221",
                "name":"维尔夫·斯科尔丁"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Lucas Englander",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1420361/",
                "abstract":"",
                "title":"卢卡斯·英格兰德（同名）奥地利,维也纳影视演员",
                "character":"饰 Horst",
                "uri":"douban://douban.com/celebrity/1420361?subject_id=34661272",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/pBVBopwNejdIcel_avatar_uploaded1563621644.62.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/pBVBopwNejdIcel_avatar_uploaded1563621644.62.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/pBVBopwNejdIcel_avatar_uploaded1563621644.62.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1420361/",
                "type":"celebrity",
                "id":"1420361",
                "name":"卢卡斯·英格兰德"
            },
            {
                "user":null,
                "roles":[
                    "演员",
                    "配音"
                ],
                "latin_name":"Fiona Glascott",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1094753/",
                "abstract":"菲奥娜·格拉斯科特是一位爱尔兰女演员，曾因为2003年电视电影《金色记忆》被提名爱尔兰电影和电视大奖...",
                "title":"菲奥娜·格拉斯科特（同名）爱尔兰,沃特福德影视演员",
                "character":"饰 Minerva McGonagall",
                "uri":"douban://douban.com/celebrity/1094753?subject_id=27300534",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1444161826.87.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1444161826.87.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1444161826.87.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1094753/",
                "type":"celebrity",
                "id":"1094753",
                "name":"菲奥娜·格拉斯科特"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Matthias Brenner",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1068895/",
                "abstract":"",
                "title":"马提亚斯·布伦纳（同名）德国,迈宁根影视演员",
                "character":"饰 Otto",
                "uri":"douban://douban.com/celebrity/1068895?subject_id=27274640",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1541785759.98.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1541785759.98.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1541785759.98.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1068895/",
                "type":"celebrity",
                "id":"1068895",
                "name":"马提亚斯·布伦纳"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Peter Simonischek",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1155835/",
                "abstract":"",
                "title":"彼得·西蒙尼舍克（同名）奥地利,格拉茨影视演员",
                "character":"饰 Warder",
                "uri":"douban://douban.com/celebrity/1155835?subject_id=27361718",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/p1462781891.91.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/p1462781891.91.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/p1462781891.91.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1155835/",
                "type":"celebrity",
                "id":"1155835",
                "name":"彼得·西蒙尼舍克"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Jacqui Boatswain",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1278852/",
                "abstract":"",
                "title":"雅基·波特斯万（同名）英国,英格兰,贝德福德影视演员",
                "character":"饰 Ida Webb",
                "uri":"douban://douban.com/celebrity/1278852?subject_id=27507131",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1488428684.77.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1488428684.77.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1488428684.77.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1278852/",
                "type":"celebrity",
                "id":"1278852",
                "name":"雅基·波特斯万"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Hebe Beardsall",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1315461/",
                "abstract":"",
                "title":"赫柏·贝尔德索尔（同名）None影视演员",
                "character":"饰 Ariana Dumbledore",
                "uri":"douban://douban.com/celebrity/1315461?subject_id=27485671",
                "cover_url":"https://img1.doubanio.com/view/celebrity/raw/public/p1590441078.67.jpg",
                "avatar":{
                    "large":"https://img1.doubanio.com/view/celebrity/raw/public/p1590441078.67.jpg",
                    "normal":"https://img1.doubanio.com/view/celebrity/raw/public/p1590441078.67.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1315461/",
                "type":"celebrity",
                "id":"1315461",
                "name":"赫柏·贝尔德索尔"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1107683/",
                "abstract":"",
                "title":"Manuel Klein（同名）德国,巴伐利亚,奥格斯堡影视演员",
                "character":"饰 Tall Auror",
                "uri":"douban://douban.com/celebrity/1107683?subject_id=27313502",
                "cover_url":"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png",
                "avatar":{
                    "large":"https://img2.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                    "normal":"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1107683/",
                "type":"celebrity",
                "id":"1107683",
                "name":"Manuel Klein"
            },
            {
                "user":null,
                "roles":[
                    "演员"
                ],
                "latin_name":"Kevin Guthrie",
                "author":null,
                "url":"https://movie.douban.com/celebrity/1335226/",
                "abstract":"Kevin was born and brought up in his hometown of Neilston, Paisley in Scotland. The son of Gordon...",
                "title":"凯文·格思里（同名）Scotland,Paisley,Neilston影视演员",
                "character":"演员",
                "uri":"douban://douban.com/celebrity/1335226?subject_id=27549052",
                "cover_url":"https://img2.doubanio.com/view/celebrity/raw/public/pilAA6kYB3Qccel_avatar_uploaded1381017414.1.jpg",
                "avatar":{
                    "large":"https://img2.doubanio.com/view/celebrity/raw/public/pilAA6kYB3Qccel_avatar_uploaded1381017414.1.jpg",
                    "normal":"https://img2.doubanio.com/view/celebrity/raw/public/pilAA6kYB3Qccel_avatar_uploaded1381017414.1.jpg"
                },
                "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/celebrity/1335226/",
                "type":"celebrity",
                "id":"1335226",
                "name":"凯文·格思里"
            }
        ],
        photoData: {
            photos:[
                {
                    "read_count":8265,
                    "image":{
                        "large":{
                            "url":"https://img9.doubanio.com/view/photo/l/public/p2832344254.jpg",
                            "width":1600,
                            "size":0,
                            "height":1066
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img9.doubanio.com/view/photo/s/public/p2832344254.jpg",
                            "width":600,
                            "size":0,
                            "height":400
                        },
                        "normal":{
                            "url":"https://img9.doubanio.com/view/photo/m/public/p2832344254.jpg",
                            "width":600,
                            "size":0,
                            "height":400
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-01-08 02:30:36",
                    "collections_count":2,
                    "reshares_count":1,
                    "id":"2832344254",
                    "author":{
                        "loc":{
                            "uid":"beijing",
                            "id":"108288",
                            "name":"北京"
                        },
                        "kind":"user",
                        "name":"Houson",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/4446419/",
                        "reg_time":"2009-06-20 17:16:32",
                        "uri":"douban://douban.com/user/4446419",
                        "avatar":"https://img2.doubanio.com/icon/up4446419-11.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"4446419",
                        "uid":"houson"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2832344254/",
                    "url":"https://movie.douban.com/photos/photo/2832344254/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2832344254",
                    "likers_count":30,
                    "reactions_count":30,
                    "comments_count":33,
                    "position":9
                },
                {
                    "read_count":12007,
                    "image":{
                        "large":{
                            "url":"https://img1.doubanio.com/view/photo/l/public/p2869096369.jpg",
                            "width":867,
                            "size":0,
                            "height":1300
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img1.doubanio.com/view/photo/s/public/p2869096369.jpg",
                            "width":400,
                            "size":0,
                            "height":600
                        },
                        "normal":{
                            "url":"https://img1.doubanio.com/view/photo/m/public/p2869096369.jpg",
                            "width":400,
                            "size":0,
                            "height":600
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-03-02 17:59:50",
                    "collections_count":1,
                    "reshares_count":0,
                    "id":"2869096369",
                    "author":{
                        "loc":{
                            "uid":"beijing",
                            "id":"108288",
                            "name":"北京"
                        },
                        "kind":"user",
                        "name":"Houson",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/4446419/",
                        "reg_time":"2009-06-20 17:16:32",
                        "uri":"douban://douban.com/user/4446419",
                        "avatar":"https://img2.doubanio.com/icon/up4446419-11.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"4446419",
                        "uid":"houson"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2869096369/",
                    "url":"https://movie.douban.com/photos/photo/2869096369/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2869096369",
                    "likers_count":26,
                    "reactions_count":26,
                    "comments_count":24,
                    "position":313
                },
                {
                    "read_count":2610,
                    "image":{
                        "large":{
                            "url":"https://img2.doubanio.com/view/photo/l/public/p2870147101.jpg",
                            "width":1000,
                            "size":0,
                            "height":419
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img2.doubanio.com/view/photo/s/public/p2870147101.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "normal":{
                            "url":"https://img2.doubanio.com/view/photo/m/public/p2870147101.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-03-21 16:21:28",
                    "collections_count":0,
                    "reshares_count":0,
                    "id":"2870147101",
                    "author":{
                        "loc":{
                            "uid":"praha",
                            "id":"128156",
                            "name":"Praha"
                        },
                        "kind":"user",
                        "name":"Orlo",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/179495030/",
                        "reg_time":"2018-06-04 17:59:56",
                        "uri":"douban://douban.com/user/179495030",
                        "avatar":"https://img1.doubanio.com/icon/up179495030-47.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"179495030",
                        "uid":"179495030"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"皮克特抱着魔杖逃跑",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2870147101/",
                    "url":"https://movie.douban.com/photos/photo/2870147101/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2870147101",
                    "likers_count":18,
                    "reactions_count":18,
                    "comments_count":15,
                    "position":304
                },
                {
                    "read_count":708,
                    "image":{
                        "large":{
                            "url":"https://img1.doubanio.com/view/photo/l/public/p2871124268.jpg",
                            "width":1600,
                            "size":0,
                            "height":670
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img1.doubanio.com/view/photo/s/public/p2871124268.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "normal":{
                            "url":"https://img1.doubanio.com/view/photo/m/public/p2871124268.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-04-08 02:50:48",
                    "collections_count":0,
                    "reshares_count":1,
                    "id":"2871124268",
                    "author":{
                        "loc":{
                            "uid":"beijing",
                            "id":"108288",
                            "name":"北京"
                        },
                        "kind":"user",
                        "name":"Houson",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/4446419/",
                        "reg_time":"2009-06-20 17:16:32",
                        "uri":"douban://douban.com/user/4446419",
                        "avatar":"https://img2.doubanio.com/icon/up4446419-11.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"4446419",
                        "uid":"houson"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2871124268/",
                    "url":"https://movie.douban.com/photos/photo/2871124268/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2871124268",
                    "likers_count":11,
                    "reactions_count":11,
                    "comments_count":10,
                    "position":3
                },
                {
                    "read_count":2604,
                    "image":{
                        "large":{
                            "url":"https://img2.doubanio.com/view/photo/l/public/p2870796852.jpg",
                            "width":1000,
                            "size":0,
                            "height":418
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img2.doubanio.com/view/photo/s/public/p2870796852.jpg",
                            "width":600,
                            "size":0,
                            "height":250
                        },
                        "normal":{
                            "url":"https://img2.doubanio.com/view/photo/m/public/p2870796852.jpg",
                            "width":600,
                            "size":0,
                            "height":250
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-04-02 11:16:13",
                    "collections_count":0,
                    "reshares_count":2,
                    "id":"2870796852",
                    "author":{
                        "loc":{
                            "uid":"praha",
                            "id":"128156",
                            "name":"Praha"
                        },
                        "kind":"user",
                        "name":"Orlo",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/179495030/",
                        "reg_time":"2018-06-04 17:59:56",
                        "uri":"douban://douban.com/user/179495030",
                        "avatar":"https://img1.doubanio.com/icon/up179495030-47.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"179495030",
                        "uid":"179495030"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"盖勒特·格林德沃",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2870796852/",
                    "url":"https://movie.douban.com/photos/photo/2870796852/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2870796852",
                    "likers_count":10,
                    "reactions_count":10,
                    "comments_count":30,
                    "position":2
                },
                {
                    "read_count":989,
                    "image":{
                        "large":{
                            "url":"https://img9.doubanio.com/view/photo/l/public/p2870880985.jpg",
                            "width":1600,
                            "size":0,
                            "height":670
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img9.doubanio.com/view/photo/s/public/p2870880985.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "normal":{
                            "url":"https://img9.doubanio.com/view/photo/m/public/p2870880985.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-04-03 21:56:30",
                    "collections_count":0,
                    "reshares_count":0,
                    "id":"2870880985",
                    "author":{
                        "loc":{
                            "uid":"zhengzhou",
                            "id":"118237",
                            "name":"郑州"
                        },
                        "kind":"user",
                        "name":"小小豪力",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/201194055/",
                        "reg_time":"2019-08-05 21:23:38",
                        "uri":"douban://douban.com/user/201194055",
                        "avatar":"https://img1.doubanio.com/icon/up201194055-9.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"201194055",
                        "uid":"201194055"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2870880985/",
                    "url":"https://movie.douban.com/photos/photo/2870880985/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2870880985",
                    "likers_count":11,
                    "reactions_count":11,
                    "comments_count":11,
                    "position":136
                },
                {
                    "read_count":4001,
                    "image":{
                        "large":{
                            "url":"https://img9.doubanio.com/view/photo/l/public/p2869096366.jpg",
                            "width":867,
                            "size":0,
                            "height":1300
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img9.doubanio.com/view/photo/s/public/p2869096366.jpg",
                            "width":400,
                            "size":0,
                            "height":600
                        },
                        "normal":{
                            "url":"https://img9.doubanio.com/view/photo/m/public/p2869096366.jpg",
                            "width":400,
                            "size":0,
                            "height":600
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-03-02 17:59:48",
                    "collections_count":3,
                    "reshares_count":0,
                    "id":"2869096366",
                    "author":{
                        "loc":{
                            "uid":"beijing",
                            "id":"108288",
                            "name":"北京"
                        },
                        "kind":"user",
                        "name":"Houson",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/4446419/",
                        "reg_time":"2009-06-20 17:16:32",
                        "uri":"douban://douban.com/user/4446419",
                        "avatar":"https://img2.doubanio.com/icon/up4446419-11.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"4446419",
                        "uid":"houson"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2869096366/",
                    "url":"https://movie.douban.com/photos/photo/2869096366/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2869096366",
                    "likers_count":11,
                    "reactions_count":11,
                    "comments_count":11,
                    "position":316
                },
                {
                    "read_count":1327,
                    "image":{
                        "large":{
                            "url":"https://img9.doubanio.com/view/photo/l/public/p2869096365.jpg",
                            "width":867,
                            "size":0,
                            "height":1300
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img9.doubanio.com/view/photo/s/public/p2869096365.jpg",
                            "width":400,
                            "size":0,
                            "height":600
                        },
                        "normal":{
                            "url":"https://img9.doubanio.com/view/photo/m/public/p2869096365.jpg",
                            "width":400,
                            "size":0,
                            "height":600
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-03-02 17:59:48",
                    "collections_count":0,
                    "reshares_count":1,
                    "id":"2869096365",
                    "author":{
                        "loc":{
                            "uid":"beijing",
                            "id":"108288",
                            "name":"北京"
                        },
                        "kind":"user",
                        "name":"Houson",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/4446419/",
                        "reg_time":"2009-06-20 17:16:32",
                        "uri":"douban://douban.com/user/4446419",
                        "avatar":"https://img2.doubanio.com/icon/up4446419-11.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"4446419",
                        "uid":"houson"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2869096365/",
                    "url":"https://movie.douban.com/photos/photo/2869096365/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2869096365",
                    "likers_count":10,
                    "reactions_count":10,
                    "comments_count":1,
                    "position":6
                },
                {
                    "read_count":589,
                    "image":{
                        "large":{
                            "url":"https://img1.doubanio.com/view/photo/l/public/p2871124288.jpg",
                            "width":1600,
                            "size":0,
                            "height":658
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img1.doubanio.com/view/photo/s/public/p2871124288.jpg",
                            "width":600,
                            "size":0,
                            "height":247
                        },
                        "normal":{
                            "url":"https://img1.doubanio.com/view/photo/m/public/p2871124288.jpg",
                            "width":600,
                            "size":0,
                            "height":247
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-04-08 02:51:29",
                    "collections_count":0,
                    "reshares_count":0,
                    "id":"2871124288",
                    "author":{
                        "loc":{
                            "uid":"beijing",
                            "id":"108288",
                            "name":"北京"
                        },
                        "kind":"user",
                        "name":"Houson",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/4446419/",
                        "reg_time":"2009-06-20 17:16:32",
                        "uri":"douban://douban.com/user/4446419",
                        "avatar":"https://img2.doubanio.com/icon/up4446419-11.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"4446419",
                        "uid":"houson"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2871124288/",
                    "url":"https://movie.douban.com/photos/photo/2871124288/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2871124288",
                    "likers_count":9,
                    "reactions_count":9,
                    "comments_count":4,
                    "position":42
                },
                {
                    "read_count":752,
                    "image":{
                        "large":{
                            "url":"https://img9.doubanio.com/view/photo/l/public/p2870880986.jpg",
                            "width":1600,
                            "size":0,
                            "height":670
                        },
                        "raw":null,
                        "small":{
                            "url":"https://img9.doubanio.com/view/photo/s/public/p2870880986.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "normal":{
                            "url":"https://img9.doubanio.com/view/photo/m/public/p2870880986.jpg",
                            "width":600,
                            "size":0,
                            "height":251
                        },
                        "is_animated":false
                    },
                    "create_time":"2022-04-03 21:56:30",
                    "collections_count":0,
                    "reshares_count":0,
                    "id":"2870880986",
                    "author":{
                        "loc":{
                            "uid":"zhengzhou",
                            "id":"118237",
                            "name":"郑州"
                        },
                        "kind":"user",
                        "name":"小小豪力",
                        "avatar_side_icon":"",
                        "url":"https://www.douban.com/people/201194055/",
                        "reg_time":"2019-08-05 21:23:38",
                        "uri":"douban://douban.com/user/201194055",
                        "avatar":"https://img1.doubanio.com/icon/up201194055-9.jpg",
                        "is_club":false,
                        "type":"user",
                        "id":"201194055",
                        "uid":"201194055"
                    },
                    "is_collected":false,
                    "subtype":"photo",
                    "type":"photo",
                    "owner_uri":"douban://douban.com/movie/26147418",
                    "status":null,
                    "reaction_type":0,
                    "description":"",
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/photo/2870880986/",
                    "url":"https://movie.douban.com/photos/photo/2870880986/",
                    "reply_limit":"A",
                    "uri":"douban://douban.com/photo/2870880986",
                    "likers_count":7,
                    "reactions_count":7,
                    "comments_count":9,
                    "position":135
                }
            ],
            total:442
        },
        comments: {
            total:28024,
            interests:[
                {
                    "comment":"如果格林德沃了解一点东方文化或者来过中国，经过哪个王府门口，也该知道麒麟是双生。",
                    "rating":{
                        "count":1,
                        "max":5,
                        "value":4,
                        "star_count":4
                    },
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/movie/26147418/interest/3306678034",
                    "show_time_tip":false,
                    "is_voted":false,
                    "uri":"douban://douban.com/movie/26147418/interest/3306678034",
                    "platforms":[
        
                    ],
                    "vote_count":3668,
                    "create_time":"2022-04-08 02:21:59",
                    "status":"done",
                    "user":{
                        "loc":{
                            "uid":"lahabana",
                            "id":"128155",
                            "name":"La Habana"
                        },
                        "reg_time":"2011-03-14 21:57:33",
                        "followed":false,
                        "name":"✌🏻☹️",
                        "uid":"chezhevip",
                        "url":"https://www.douban.com/people/50116284/",
                        "gender":"M",
                        "uri":"douban://douban.com/user/50116284",
                        "kind":"user",
                        "id":"50116284",
                        "remark":"",
                        "avatar":"https://img2.doubanio.com/icon/user_large.jpg",
                        "is_club":false,
                        "type":"user",
                        "avatar_side_icon":"",
                        "in_blacklist":false
                    },
                    "recommend_reason":"",
                    "user_done_desc":"",
                    "id":"3306678034",
                    "wechat_timeline_share":"screenshot"
                },
                {
                    "comment":"《阿不福思：是的，我们有一个孩子》",
                    "rating":{
                        "count":1,
                        "max":5,
                        "value":3,
                        "star_count":3
                    },
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/movie/26147418/interest/3306705385",
                    "show_time_tip":false,
                    "is_voted":false,
                    "uri":"douban://douban.com/movie/26147418/interest/3306705385",
                    "platforms":[
        
                    ],
                    "vote_count":2476,
                    "create_time":"2022-04-08 03:18:52",
                    "status":"done",
                    "user":{
                        "loc":{
                            "uid":"shenzhen",
                            "id":"118282",
                            "name":"深圳"
                        },
                        "reg_time":"2014-07-06 23:38:17",
                        "followed":false,
                        "name":"🍐无原上草",
                        "uid":"92343255",
                        "url":"https://www.douban.com/people/92343255/",
                        "gender":"U",
                        "uri":"douban://douban.com/user/92343255",
                        "kind":"user",
                        "id":"92343255",
                        "remark":"",
                        "avatar":"https://img1.doubanio.com/icon/up92343255-7.jpg",
                        "is_club":false,
                        "type":"user",
                        "avatar_side_icon":"",
                        "in_blacklist":false
                    },
                    "recommend_reason":"",
                    "user_done_desc":"",
                    "id":"3306705385",
                    "wechat_timeline_share":"screenshot"
                },
                {
                    "comment":"逐渐演变成服务GGAD的外传了，主客颠倒得别太严重……现在真的很想问一句：神奇动物在哪里？？？",
                    "rating":{
                        "count":1,
                        "max":5,
                        "value":4,
                        "star_count":4
                    },
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/movie/26147418/interest/2626995606",
                    "show_time_tip":false,
                    "is_voted":false,
                    "uri":"douban://douban.com/movie/26147418/interest/2626995606",
                    "platforms":[
        
                    ],
                    "vote_count":1919,
                    "create_time":"2022-04-08 03:25:18",
                    "status":"done",
                    "user":{
                        "loc":null,
                        "reg_time":"2019-06-27 12:26:36",
                        "followed":false,
                        "name":"小狗沐浴直拍",
                        "uid":"198622263",
                        "url":"https://www.douban.com/people/198622263/",
                        "gender":"U",
                        "uri":"douban://douban.com/user/198622263",
                        "kind":"user",
                        "id":"198622263",
                        "remark":"",
                        "avatar":"https://img2.doubanio.com/icon/up198622263-2.jpg",
                        "is_club":false,
                        "type":"user",
                        "avatar_side_icon":"",
                        "in_blacklist":false
                    },
                    "recommend_reason":"",
                    "user_done_desc":"",
                    "id":"2626995606",
                    "wechat_timeline_share":"screenshot"
                },
                {
                    "comment":"看得好累啊，我真不知道这些人物到底在忙些什么么？他们为什么要打架！都已经拍到第三部了，至今还不知道这个系列的看点是什么？主角到底是谁？神奇动物越来越像吉祥萌物而没有任何的作用，至于邓布利多和格林德天的CP，家人们呀，这大工业糖精，我磕不动啊！结尾互摸对.大卫·叶茨，英国电影导演。曾在美国华盛顿居住一年，之后返回伦敦的国家电影电视学院学习。是著名导演...",
                    "rating":{
                        "count":1,
                        "max":5,
                        "value":5,
                        "star_count":5
                    },
                    "sharing_url":"https://www.douban.com/doubanapp/dispatch?uri=/movie/26147418/interest/3301794558",
                    "show_time_tip":false,
                    "is_voted":false,
                    "uri":"douban://douban.com/movie/26147418/interest/3301794558",
                    "platforms":[
        
                    ],
                    "vote_count":1993,
                    "create_time":"2022-04-08 16:41:55",
                    "status":"done",
                    "user":{
                        "loc":{
                            "uid":"yokohama",
                            "id":"128485",
                            "name":"Yokohama"
                        },
                        "reg_time":"2017-10-29 12:35:42",
                        "followed":false,
                        "name":"得",
                        "uid":"168876389",
                        "url":"https://www.douban.com/people/168876389/",
                        "gender":"U",
                        "uri":"douban://douban.com/user/168876389",
                        "kind":"user",
                        "id":"168876389",
                        "remark":"",
                        "avatar":"https://img9.doubanio.com/icon/up168876389-4.jpg",
                        "is_club":false,
                        "type":"user",
                        "avatar_side_icon":"",
                        "in_blacklist":false
                    },
                    "recommend_reason":"",
                    "user_done_desc":"",
                    "id":"3301794558",
                    "wechat_timeline_share":"screenshot"
                }
            ]
        }
    },

    /**
     * 生命周期函数--监听页面加载
     */
    onLoad(options) {
        const movie = JSON.parse(options.movie);
        console.log(movie)
        this.setData({ title: movie.title });
        console.log(this.data.clipDesc)
    },

    clipDescAction: function() {
        this.setData({ clipDesc: !this.data.clipDesc })
        console.log(this.data.clipDesc)
    }
})